### ISSUE TITLE
Create dbt converter for Airbyte Facebook Marketing source connector

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte-dbt-models#10]
The goal of this task is to ensure the Airbyte Facebook Ads connector output can be used to run [Fivetran's dbt analytical model](https://hub.getdbt.com/fivetran/facebook/latest/).

**Definition of Done:** 
* Create a pull request that adds new tables or views, enabling the execution of Fiventran's dbt with Airbyte output data.
* Update the documentation inside the connector folder to explain how to configure the user dbt package to run the analytical model.

**Resources:** 
* Check example of how it was done for [Zendesk Support](link) connector

**Comment by FloDevelops** [comment]
@marcosmarxm I'll get that own 😉

**Comment by FloDevelops** [comment]
@marcosmarxm 

## Step 1: Identify what streams

[fivetran/dbt_facebook_ads_source sources](https://github.com/fivetran/dbt_facebook_ads_source/blob/main/models/src_facebook_ads.yml)

| Fivetran         | Airbyte      |
| ---------------- | ------------ |
| account_history  | ad_account   |
| ad_history       | ads          |
| ad_set_history   | ad_sets      |
| basic_ad         | ads_insights |
| campaign_history | campaigns    |
| creative_history | ad_creatives |

✅ All the required tables appear to be in Airbyte.

**Comment by marcosmarxm** [comment]
Let's go to second step @FloDevelops feel free to reach me in Airbyte Slack I can share a database with sample data for you to run tests :)

**Comment by topefolorunso** [comment]
No update in 5 days. Can I work on this next? @marcosmarxm

**Comment by FloDevelops** [comment]
@marcosmarxm @topefolorunso here is the update!

It's going well! I have the accounts and ads tables migrated in [my repo](https://github.com/FloDevelops/airbyte-dbt-models/commit/98657f69d4016760de1e0be047e3c4c98f5bd540)

**Comment by marcosmarxm** [comment]
I'm going to take a look @FloDevelops

**Comment by FloDevelops** [comment]
Quick new update @marcosmarxm 
The ad_sets, campaigns and creatives tables are also [migrated now](https://github.com/FloDevelops/airbyte-dbt-models/commit/4489b4b40a566c10b711fb8b1d649daae89e55e7#diff-c70096031423171607652143921e94f99a650f22159e60fc062738b42569875d), however some columns from the creatives are not in the Airbyte schema, or under different names hard to recognize for sure (page_link, template_page_link, template_app_link_spec_ios, ...), unless they are just empty JSON fields in the test database (template_url_spec?).

Let me know if you have any idea, else I'll come back to it later and work on the basic_ad insights model.

**Comment by FloDevelops** [comment]
The basic ad insights staging model is ready! ✅

It starts to look good:
<img width="866" alt="image" src="https://github.com/user-attachments/assets/17be3583-7ecc-4bfb-a78f-a2b537da1426">

Next steps are:
- find the missing fields at the creative level
- replace specific database functions to cross-database macros, especially json functions (@marcosmarxm I found it in [fivetran_utils](https://github.com/fivetran/dbt_fivetran_utils/blob/v0.4.10/macros/json_extract.sql) as it does not exists in core)
- use the sources created by Airbyte while keeping the ability to union same-level tables accros databases or schemas
- test the Fivetran analytical model and solve bugs
- update the documentation (model yaml files + README)

**Comment by marcosmarxm** [comment]
@FloDevelops awesome work! Let me know if you need any help!

**Comment by FloDevelops** [comment]
Hi @marcosmarxm!
I left the union of multiple Facebook Ads schemas aside for now to use the sources you provided.

This is looking very good now:

- [x] find the missing fields at the creative level
- [x] replace specific database functions to cross-database macros, especially json functions 
- [x] use the sources created by Airbyte
- [x] test the Fivetran analytical model and solve bugs
- [ ] final QA
- [ ] (restore the ability to union same-level tables accros databases or schemas)

## Step 3: Write instructions

- [ ] update the documentation (model yaml files + README)

> Please note some functionalities may not be transferrable from the Fivetran extract to Airbyte's, including the url_tags field that in Fivetran is a JSON array of URL parameters of different types (AD_PAGE_LINK, AD_CAROUSEL_PAGE_LINK, AD, AD_VIDEO) while in Airbyte such url_tags types do not seem to be available.

**Comment by FloDevelops** [comment]
@marcosmarxm PR sent for review 😉: https://github.com/airbytehq/airbyte-dbt-models/pull/55
