### ISSUE TITLE
Create dbt converter for Airbyte Google Ads source connector

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte-dbt-models#12]
The goal of this task is to ensure the Airbyte Google Ads connector output can be used to run [Fivetran's dbt analytical model](https://hub.getdbt.com/fivetran/google_ads/latest/).

**Definition of Done:** 
* Create a pull request that adds new tables or views, enabling the execution of Fiventran's dbt with Airbyte output data.
* Update the documentation inside the connector folder to explain how to configure the user dbt package to run the analytical model.

**Resources:** 
* Check example of how it was done for [Zendesk Support](link) connector

**Comment by ash-x4** [comment]
I would like to work on this please @marcosmarxm! 🙇

**Comment by ash-x4** [comment]
Hey , Does this look good @marcosmarxm ? 🤔 
LMK incase modifcations are required!

| Fivetran Table (Stream)     | Airbyte Stream (Class)        |
|-----------------------------|-------------------------------|
| ad_stats                    | AdGroupAd                     |
| ad_history                  | AdGroupAd                     |
| ad_group_history            | AdGroup                       |
| campaign_history            | Campaign                      |
| account_history             | Customer                      |
| ad_group_criterion_history  | AdGroupCriterion              |
| ad_group_stats              | AdGroup                       |
| campaign_stats              | Campaign                      |
| keyword_stats               | AdGroupCriterion              |
| account_stats               | Customer                      |

Links :
 [DBT GOOGLE ADS](https://github.com/fivetran/dbt_google_ads_source/blob/main/models/src_google_ads.yml)
[Airbyte Streams](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-google-ads/source_google_ads/streams.py)
[Airbyte DBT Model](https://github.com/airbytehq/airbyte-dbt-models/tree/main/connectors/source_google_ads/models/source)

**Comment by marcosmarxm** [comment]
Looks good, probably the tables generated by Fivetran are broken into smaller versions and Airbyte keep into a single one like AdGroupAd. @ash-x4 can you starting checking if the columns are correct too? Let's start with `ads_stats` and `ad_history`

**Comment by marcosmarxm** [comment]
@ash-x4 do you need any further help or assistance here?

**Comment by ash-x4** [comment]
@marcosmarxm  Thanks for asking , I am working on step 2 it will take some time.

**Comment by marcosmarxm** [comment]
No problem! Thanks for the update

**Comment by marcosmarxm** [comment]
@ash-x4 can you provide an update about the tasks?

**Comment by ombhardwajj** [comment]
Hey @ash-x4 Incase you are facing difficulties , feel free to ping me on Slack ! I am ready to offer any possible help or we can team up and work on it!!

**Comment by yachanaarora04** [comment]
Hey @marcosmarxm 
Incase @ash-x4 is inactive or no more working on this , I would like to work on this!
I am quite experienced at these transformations!!

**Comment by ash-x4** [comment]
Sorry for all the delay @marcosmarxm 🙇 
There are many tables which need to be analysed! I have been busy and couldn't do this completely.
Thanks for opting in @yachanaarora04 , you've saved the day! You can work on this!! 🚀
