### ISSUE TITLE
Create dbt converter for Airbyte Klaviyo source connector

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte-dbt-models#17]
The goal of this task is to ensure the Airbyte Klaviyo connector output can be used to run [Fivetran's dbt analytical model](https://hub.getdbt.com/fivetran/klaviyo/latest/).

**Definition of Done:** 
* Create a pull request that adds new tables or views, enabling the execution of Fiventran's dbt with Airbyte output data.
* Update the documentation inside the connector folder to explain how to configure the user dbt package to run the analytical model.

**Resources:** 
* Check example of how it was done for [Zendesk Support](link) connector

**Comment by parthiv11** [comment]
I would like to try

**Comment by parthiv11** [comment]
### Step 1- Identify what streams
| Fivetran | Airbyte   |
|----------|-----------|
| campaign | campaigns |
| event    | events    |
| flow     | flows     |
| metric   | metrics   |
| person   | profiles  |

- next need to add `fivetran_converter/` for person table

Step2- Identify which streams 



waiting for approval @marcosmarxm to move step 2

**Comment by marcosmarxm** [comment]
@parthiv11 what is the reason to create a new table for person? Can you use a variable like:
`dbt_profiles.yaml`
```
person: "profiles"
```

Let me know if this makes sense.

**Comment by marcosmarxm** [comment]
@parthiv11, do you need any assistance or further help?
