### ISSUE TITLE
Create dbt converter for Airbyte Mailchimp source connector

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte-dbt-models#20]
The goal of this task is to ensure the Airbyte Mailchimp connector output can be used to run [Fivetran's dbt analytical model](https://hub.getdbt.com/fivetran/mailchimp/latest/).

**Definition of Done:** 
* Create a pull request that adds new tables or views, enabling the execution of Fiventran's dbt with Airbyte output data.
* Update the documentation inside the connector folder to explain how to configure the user dbt package to run the analytical model.

**Resources:** 
* Check example of how it was done for [Zendesk Support](link) connector

**Comment by 15vaibhav2003** [comment]
I would like to try out my hands on this one.
Please assign it to me @marcosmarxm  🙇

**Comment by 15vaibhav2003** [comment]
Hey @marcosmarxm 
Please confirm if this is fine!

| **Fivetran Stream**               | **Airbyte Stream**                          |
|-----------------------------------|---------------------------------------------|
| automation                        | Automations                                 |
| automation_email                  | ❌ It doesn't exist                          |
| automation_recipient              | ❌ It doesn't exist                           |
| automation_recipient_activity     | ❌ It doesn't exist                           |
| campaign                          | Campaigns                                   |
| campaign_recipient                | Campaigns (it has a column for recipients)  |
| campaign_recipient_activity       | ❌ It doesn't exist                          |
| segment                           | ❌ It doesn't exist                        |
| segment_member                    | ❌ It doesn't exist                           |
| list                              | Lists                                       |
| member                            | ❌ It doesn't exist                         |
| unsubscribe                       | ❌ It doesn't exist                           |

**Comment by marcosmarxm** [comment]
For the tables doesn't exist @15vaibhav2003 probably they're generated using json/objects fields inside the parent table.
Check for the email, recipient and recipient_activity fields inside automation in Airbyte schema please?

**Comment by 15vaibhav2003** [comment]
Hey @marcosmarxm I've checked inside the parent table and found two fields to be present! 
Please confirm if this is fine! 🙇 

| **Fivetran Stream**               | **Airbyte Stream**                          |
|-----------------------------------|---------------------------------------------|
| automation                        | Automations                                 |
| automation_email                  | Settings object within Automation (email-related fields)                        |
| automation_recipient              | Recipients object within Automation                         |
| automation_recipient_activity     | Report_summary object within Automation (activity fields)                           |
| campaign                          | Campaigns                                   |
| campaign_recipient                | Campaigns (it has a column for recipients)  |
| campaign_recipient_activity       | ❌ It doesn't exist                          |
| segment                           | ❌ It doesn't exist                        |
| segment_member                    | ❌ It doesn't exist                           |
| list                              | Lists                                       |
| member                            | list_members                        |
| unsubscribe                       | unsubscribes                          |

Waiting for your approval !!

**Comment by marcosmarxm** [comment]
@15vaibhav2003 segment and segments_members exists in airbyte schema
Check: https://github.com/airbytehq/airbyte-dbt-models/tree/main/connectors/source_mailchimp/models/source
<img width="656" alt="image" src="https://github.com/user-attachments/assets/2d61fde1-04db-4190-96a6-b7e73d616616">


The hard part is the `activity` can you check the summary has the fields Fivetran is using? Please check Mailchimp API to help you there.

**Comment by marcosmarxm** [comment]
@15vaibhav2003 did you check my last comment? Do you need any help or assistance?

**Comment by 15vaibhav2003** [comment]
@marcosmarxm  
I understand your point that `segment `and `segments_members` exist and therefore I should correct "❌ It doesn't exist" for the two fields.

But I could not find activity even in `campaigns.yaml`

Actually I did not understand when you said "can you check the summary has the fields Fivetran is using".
Do you mean if the object `report_summary` in campaign.yaml contains something like that?

Need a little clarity and help from you , then I'll be good to go!

**Comment by marcosmarxm** [comment]
Yes, you're suggesting to create a table using:
`Report_summary object within Automation (activity fields)`
Can you confirm the fields/values in this objects match the fields Fivetran is using?

I'll take a look back tomorrow to this connector.

For Campaigns can you check Mailchimp Campaigns API endpoint? If there any mention to activitiy field?

**Comment by marcosmarxm** [comment]
@15vaibhav2003 can you provide an update about the task?>

**Comment by ombhardwajj** [comment]
Hey @15vaibhav2003  Incase you are facing difficulties , feel free to ping me on Slack ! I am ready to offer any possible help or we can team up and work on it!!

**Comment by 15vaibhav2003** [comment]
Hey @marcosmarxm 
I'll make a PR in a few hours .
Thanks

**Comment by 15vaibhav2003** [comment]
Update : I am almost done! Will push a PR today!

**Comment by 15vaibhav2003** [comment]
I've linked a PR , have a look @marcosmarxm . Still some changes are required since this hasnt been tested, moreover many cloumns are not present in Airbyte tables!
