### ISSUE TITLE
Create dbt converter for Airbyte Recurly source connector

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte-dbt-models#24]
The goal of this task is to ensure the Airbyte Recurly connector output can be used to run [Fivetran's dbt analytical model](https://hub.getdbt.com/fivetran/recurly/latest/).

**Definition of Done:** 
* Create a pull request that adds new tables or views, enabling the execution of Fiventran's dbt with Airbyte output data.
* Update the documentation inside the connector folder to explain how to configure the user dbt package to run the analytical model.

**Resources:** 
* Check example of how it was done for [Zendesk Support](link) connector

**Comment by btkcodedev** [comment]
Hi I would like to take this issue

**Comment by btkcodedev** [comment]
Step 1 
Analysis:

The following tables are to be analyzed with recurly in 
https://github.com/fivetran/dbt_recurly/tree/main/models

![image](https://github.com/user-attachments/assets/4dfc361d-8e7e-493b-b4b9-ba6f16a4ae0f)

**Comment by btkcodedev** [comment]
Doubt 1 
@marcosmarxm 
We in airbyte have only `account_notes` for fivetran's `recurly_account_overview` and `recurly_account_daily_overview`, 
Also several columns are missing here? What should we do further

https://fivetran.github.io/dbt_recurly/#!/model/model.recurly.recurly__account_overview#columns

Airbyte:
![image](https://github.com/user-attachments/assets/c8ff0242-439a-4587-945f-5586f769fb8f)


Fivetran:
![image](https://github.com/user-attachments/assets/64e9f202-8fd3-4beb-9bb4-9752559b6e77)

**Comment by btkcodedev** [comment]
In whole,
| **Fivetran**                               | **Airbyte**                                    |
|--------------------------------------------|------------------------------------------------|
| `recurly__account_daily_overview`          | ❌ It doesn't exist (No `account` stream)       |
| `recurly__account_overview`                | ❌ It doesn't exist (No `account` stream)       |
| `recurly__balance_transactions`  **Depends upon:**<br>- `stg_recurly__invoice_history`<br>- `stg_recurly__line_item_history`<br>- `stg_recurly__transaction`      | **Substitute:**<br>- `invoices`<br>- `line_items`<br>- `transactions` |
| `recurly__churn_analysis` **Depends upon:**<br>- `recurly__subscription_overview`     | `-`               
| `recurly__monthly_recurring_revenue`   **Depends upon:**<br>- `recurly__balance_transactions`  <br>- `stg_recurly__account_history`  | **Substitute:**<br>- `invoices`<br>- ❌ It doesn't exist (No `account` stream)          
| `recurly__subscription_overview`  **Depends upon:**<br>- `stg_recurly__plan_history`<br>- `stg_recurly__subscription_history`<br>- `recurly__account_overview`             | **Substitute:**<br>- `plans`<br>- `subscriptions`<br>- ❌ It doesn't exist (No `account` stream)

**Comment by btkcodedev** [comment]
URL: https://fivetran.github.io/dbt_recurly/#!/model/model.recurly_source

| **Fivetran**                                    | **Airbyte**            |
|-------------------------------------------------|------------------------|
| `stg_recurly__account_balance_history.sql`      | ❌ it doesn't exist        |
| `stg_recurly__account_history.sql`              | ❌ it doesn't exist     |
| `stg_recurly__account_note_history.sql`         | `account_notes`        |
| `stg_recurly__billing_info_history.sql`         | `billing_info`         |
| `stg_recurly__coupon_discount.sql`              | `coupons`              |
| `stg_recurly__coupon_redemption_history.sql`    | ❌ it doesn't exist         |
| `stg_recurly__credit_payment_history.sql`       | `credit_payments`      |
| `stg_recurly__invoice_coupon_redemption_history.sql` | ❌ it doesn't exist          |
| `stg_recurly__invoice_history.sql`              | `invoices`             |
| `stg_recurly__invoice_subscription_history.sql` | ❌ it doesn't exist       |
| `stg_recurly__line_item_history.sql`            | `line_items`           |
| `stg_recurly__plan_currency_history.sql`        | ❌ it doesn't exist                |
| `stg_recurly__plan_history.sql`                 | `plans`                |
| `stg_recurly__subscription_add_on_history.sql`  | ❌ it doesn't exist             |
| `stg_recurly__subscription_change_history.sql`  | ❌ it doesn't exist        |
| `stg_recurly__subscription_history.sql`         | `subscriptions`        |
| `stg_recurly__transaction.sql`                  | `transactions`         |
| `stg_recurly__transaction_subscription.sql`     | ❌ it doesn't exist        |
