### ISSUE TITLE
Create dbt converter for Airbyte Recharge source connector

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte-dbt-models#25]
The goal of this task is to ensure the Airbyte Recharge connector output can be used to run [Fivetran's dbt analytical model](https://hub.getdbt.com/fivetran/recharge/latest/).

**Definition of Done:** 
* Create a pull request that adds new tables or views, enabling the execution of Fiventran's dbt with Airbyte output data.
* Update the documentation inside the connector folder to explain how to configure the user dbt package to run the analytical model.

**Resources:** 
* Check example of how it was done for [Zendesk Support](link) connector

**Comment by rytismi** [comment]
I would like to work on this.

**Comment by marcosmarxm** [comment]
All yours!

**Comment by rytismi** [comment]
Hello, I did a 1st step. A few notes, 

- a few tables are just unnested arrays on Fivetran's side, while Airbyte keeps them nested in a parent table.
-  `address_shipping_line` on Fivetran's side seems to be a union (or other transformation) of `shipping_lines_override` and `shipping_lines_conserved`
- Fivetran has `order` and `orders` for connectors created before or after 2024-06-18.
- `Subscription_history` seems to be a model of `subscription` table, checked on API docs - there is no info regarding that table.

| Fivetran        | Airbyte           | 
| ------------- |:-------------:| 
| address  | addresses |
| address_discounts | nested in `addresses` |
| address_shipping_line | nested in addresses as `shipping_lines_override` and `shipping_lines_conserved` |
| charge  | charges |
| charge_discount  | nested in `charges` as `discounts` |
| charge_line_item | nested in `charges` as `line_items` |
| charge_order_attribute | nested in `charges` as `order_attributes` |
| charge_shipping_line | nested in `charges` as `shipping_lines` |
| charge_tax_line | nested in `charges` as `tax_lines` |
| customer | customers |
| discount | discounts|
| one_time_product | onetimes |
|order (# applies to connectors created before 2024-06-18)| orders|
|orders (# applies to connectors created on or after 2024-06-18)| orders|
| order_line_item| nested in `orders` as `line_items` |
| subscription| subscriptions |
|subscription_history| subscriptions|

**Comment by marcosmarxm** [comment]
Thanks for all the research @rytismi let's move to second phase. Probably the most complicated part will be the subscription and subscription_history. I'll try to get more info about them but you can start doing the transformation for the other tables.

**Comment by ombhardwajj** [comment]
Hey @marcosmarxm 
Can I work on this issue? My PR for LinkedIn issue is already about to merge as you know...? 🙇 
@rytismi seems to be inactive since three weeks , since no update/PR has been made!!

**Comment by rytismi** [comment]
Hey @ombhardwajj, it's already merged. :D 
https://github.com/airbytehq/airbyte-dbt-models/pull/56

**Comment by ombhardwajj** [comment]
@rytismi 
Great work !!
Apologies , Missed that PR!!
