### ISSUE TITLE
Create dbt converter for Airbyte Snapchat source connector

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte-dbt-models#29]
The goal of this task is to ensure the Airbyte Snapchat connector output can be used to run [Fivetran's dbt analytical model](https://hub.getdbt.com/fivetran/snapchat/latest/).

**Definition of Done:** 
* Create a pull request that adds new tables or views, enabling the execution of Fiventran's dbt with Airbyte output data.
* Update the documentation inside the connector folder to explain how to configure the user dbt package to run the analytical model.

**Resources:** 
* Check example of how it was done for [Zendesk Support](link) connector

**Comment by Suraj-Vishwakarma70** [comment]
This seems interesting and I will work on this! @marcosmarxm

**Comment by Suraj-Vishwakarma70** [comment]
Hey @marcosmarxm 
Please see this and lmk if any modifications are needed!

| **Fivetran Stream**               | **Airbyte Stream**                          |
|-----------------------------------|---------------------------------------------|
| ad_account_history                | ❌ It doesn't exist                                  |
| ad_history                        | ads                                         |
| ad_hourly_report                  | ads_stats_hourly                            |
| ad_squad_history                  | adsquads                                    |
| ad_squad_hourly_report            | adsquads_stats_hourly                       |
| campaign_history                  | campaigns                                   |
| campaign_hourly_report            | campaigns_stats_hourly                      |
| creative_history                  | ❌ It doesn't exist                          |
| creative_url_tag_history          | ❌ It doesn't exist                          |

Note:
1) adaccounts seems to be related to present state and not history likewise for creative_history and creatives
2) we dont have tag related stuff for creative_url_tag_history 

Waiting for your approval for the next step!

**Comment by marcosmarxm** [comment]
| **Fivetran Stream**               | **Airbyte Stream**                          |
|-----------------------------------|---------------------------------------------|
| ad_account_history                |  it is called `adaccounts`                                  |
| ad_history                        | ads                                         |
| ad_hourly_report                  | ads_stats_hourly                            |
| ad_squad_history                  | adsquads                                    |
| ad_squad_hourly_report            | adsquads_stats_hourly                       |
| campaign_history                  | campaigns                                   |
| campaign_hourly_report            | campaigns_stats_hourly                      |
| creative_history                  |  `creatives`                          |
| creative_url_tag_history          | ❌ It doesn't exist                          |


Can you check Snapchat API documentation and compare with Fivetran columns for `creative_url_tag_history` from where these values come from?

**Comment by marcosmarxm** [comment]
@Suraj-Vishwakarma70 the `creative_url_tag_history` is a table created from `created_history.web_view_properties.url`.
Example: `www.example.com/product?utm_source=new+subscribers&utm_medium=email&utm_campaign=black+friday+sale&utm_content=first+cta+button`

The table will be:
| key | value |
| --- | -- |
| utm_source | new+subscribers |
| utm_medium | email |
...

**Comment by marcosmarxm** [comment]
@Suraj-Vishwakarma70 can you give an update about the status of this task?

**Comment by Suraj-Vishwakarma70** [comment]
Hey @marcosmarxm 
I didnt quite understand what to do with creative_url_tag_history....Since we dont have that table directly , we will need to directly make a new table by extracting URL parameters from the `web_view_properties.url` field in the `creative_history `stream ....or something like thar right?

Apart from this I'll make a PR with commits of transformations for all other tables today!
