### ISSUE TITLE
Create dbt converter for Airbyte Amplitude source connector

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte-dbt-models#8]
The goal of this task is to ensure the Airbyte Amplitude connector output can be used to run [Fivetran's dbt analytical model](https://hub.getdbt.com/fivetran/amplitude/latest/).

**Definition of Done:** 
* Create a pull request that adds new tables or views, enabling the execution of Fiventran's dbt with Airbyte output data.
* Update the documentation inside the connector folder to explain how to configure the user dbt package to run the analytical model.

**Resources:** 
* Check example of how it was done for [Zendesk Support](link) connector 
```[tasklist]
### Tasks
- [x] event
- [x] event_type
```

**Comment by topefolorunso** [comment]
Can I claim this?

**Comment by topefolorunso** [comment]
@marcosmarxm For step 1, Fivetran only has needs two tables

| Fivetran | Airbyte    | 
|--------- |------------|
| event   | events |
| event_type   | :x: it doesn't exist |

**Comment by marcosmarxm** [comment]
You're correct usually Fivetran create child tables for important objects inside the schema. Can you check if the `events` table have a nested object `type`?

**Comment by topefolorunso** [comment]
I don't see any nested object type in the events table - https://fivetran.github.io/dbt_amplitude_source/#!/model/model.amplitude_source.stg_amplitude__event#columns

Am I looking in the wrong place?

**Comment by topefolorunso** [comment]
Oh you mean in Airbyte? Yes. The following are nested in Airbyte.

- group_properties
- user_properties
- groups
- event_properties
- data
- plan
- global_user_properties

**Comment by marcosmarxm** [comment]
Let's check `event_properties` and compare with the fields used by the SQL statement.

**Comment by topefolorunso** [comment]
unable to access the details of `event_properties`, even from [amplitude api doc ](https://amplitude.com/docs/apis/analytics/export#response)

Can I do a test read maybe to get an idea?

**Comment by topefolorunso** [comment]
For event table;

the following columns are not present in airbyte:
- _fivetran_synced
- project_name
- event_type_id

others are present except the following which are to be renamed:
- $insert_id AS _insert_id
- $schema AS schema
- adid AS ad_id
- event_id AS id
- groups AS group_types

**Comment by marcosmarxm** [comment]
The fivetran_synced is not relevant for the models.

`project_name` => you can use the column `app` it isn't the text representation but it contains the Project ID which is the info we're looking for.

The `event_type_id` (need investigat the raw response but it isn't provided in the API response documentation) you can join `events` with `event_type` table. Something: `events.event_type == event_type.value`

**Comment by topefolorunso** [comment]
Done. Waiting to merge https://github.com/airbytehq/airbyte/pull/43400 to proceed. 

At this point, events table now depend on event_type table.

**Comment by topefolorunso** [comment]
@marcosmarxm Can you assign me another issue while waiting for the merge?
