### ISSUE TITLE
Create dbt converter for Airbyte Asana source connector

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte-dbt-models#9]
The goal of this task is to ensure the Airbyte Asana connector output can be used to run [Fivetran's dbt analytical model](https://hub.getdbt.com/fivetran/asana/latest/).

**Definition of Done:** 
* Create a pull request that adds new tables or views, enabling the execution of Fiventran's dbt with Airbyte output data.
* Update the documentation inside the connector folder to explain how to configure the user dbt package to run the analytical model.

**Resources:** 
* Check example of how it was done for [Zendesk Support](link) connector

**Comment by pangeran-bottor** [comment]
### Step 1: Identify what streams

---

| Fivetran       | Airbyte        |
|----------------|----------------|
| project        | projects        |
| project_task   | tasks   |
| section        | sections        |
| story          | stories          |
| tag            | tags            |
| task           | tasks           |
| task_follower  | tasks.followers  |
| task_section   | ❌ it doesn't exist  |
| task_tag       | tasks.tags       |
| team           | teams          |
| user           | users           |

Hi @marcosmarxm , please review this. Thank you

**Comment by marcosmarxm** [comment]
For the `task_section` @pangeran-bottor you'll need to include a new field in `tasks`. 
Today it is missing but there is a object in Tasks endpoint: https://developers.asana.com/reference/tasks
Let me know if you need help submitting the PR to add this field to Asana -> Tasks stream.

**Comment by pangeran-bottor** [comment]
Hi @marcosmarxm , as I was investigating the connector error (it's working fine now), just found out that `section` can be extracted from the `memberships` field. Sorry for missing that. I guess I can proceed to the next steps then?

**Comment by pangeran-bottor** [comment]
Hi @marcosmarxm , I still haven't got the credentials to the test instance. I just started to do the initial converter for `project` in this [commit](https://github.com/airbytehq/airbyte-dbt-models/pull/53/commits/72115b7e5f68ba3108d6ed84238853068b9d4be3).
Kindly take a look if this close to what intended. If so, I will apply this for all the models
